[package]
name = "packed_vec"
version = "0.1.0"
authors = ["Gabriela Alexandra Moldovan <gabi_250@live.com>"]

[dependencies]
num-traits = "0.2"
rand = "0.3"
serde = { version="1.0", features=["derive"], optional=true }
